// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaaZXA-DoxptyGBKt0m-UkZuZLCOBc3OE',
    appId: '1:1077202650632:web:0c5da87373010c0e0b33bd',
    messagingSenderId: '1077202650632',
    projectId: 'maps-app-858ed',
    authDomain: 'maps-app-858ed.firebaseapp.com',
    storageBucket: 'maps-app-858ed.appspot.com',
    measurementId: 'G-HCZT1WL765',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsRRb0ASDgJX7KH5doICnzDEQSZlwmbG4',
    appId: '1:1077202650632:android:a06c6d1821ac535f0b33bd',
    messagingSenderId: '1077202650632',
    projectId: 'maps-app-858ed',
    storageBucket: 'maps-app-858ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-IOQK2JOPD39UJm2iNGn3hrLNx5YkQ2w',
    appId: '1:1077202650632:ios:81b44d14246579720b33bd',
    messagingSenderId: '1077202650632',
    projectId: 'maps-app-858ed',
    storageBucket: 'maps-app-858ed.appspot.com',
    iosBundleId: 'com.example.maps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-IOQK2JOPD39UJm2iNGn3hrLNx5YkQ2w',
    appId: '1:1077202650632:ios:81b44d14246579720b33bd',
    messagingSenderId: '1077202650632',
    projectId: 'maps-app-858ed',
    storageBucket: 'maps-app-858ed.appspot.com',
    iosBundleId: 'com.example.maps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaaZXA-DoxptyGBKt0m-UkZuZLCOBc3OE',
    appId: '1:1077202650632:web:a6b42aca73e91f0e0b33bd',
    messagingSenderId: '1077202650632',
    projectId: 'maps-app-858ed',
    authDomain: 'maps-app-858ed.firebaseapp.com',
    storageBucket: 'maps-app-858ed.appspot.com',
    measurementId: 'G-RHEGGXKM4G',
  );
}
